"""Initial DB

Revision ID: 8db44216f436
Revises: 
Create Date: 2023-01-14 22:25:44.133539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db44216f436'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('timezone', sa.Integer(), nullable=True),
    sa.Column('first_met', sa.String(), nullable=True),
    sa.Column('last_activity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('cmd', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('when_added', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('warn_before_expired', sa.Integer(), nullable=True),
    sa.Column('last_checked', sa.String(), nullable=True),
    sa.Column('last_ok', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('cert_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers')
    op.drop_table('activity')
    op.drop_table('users')
    # ### end Alembic commands ###
